import React, { useState, useEffect } from 'react';
import { 
  FileText, 
  Copy, 
  Check, 
  X, 
  Printer, 
  GitCommit, 
  AlertTriangle, 
  Users, 
  Sparkles,
  ArrowRight
} from 'lucide-react';
import { ProjectContextBrief } from '../../types';
import { projectApi } from '../../services/api';
import { LoadingState } from '../common/LoadingState';

interface ProjectBriefModalProps {
  projectId: string;
  onClose: () => void;
}

export const ProjectBriefModal: React.FC<ProjectBriefModalProps> = ({ projectId, onClose }) => {
  const [brief, setBrief] = useState<ProjectContextBrief | null>(null);
  const [loading, setLoading] = useState<boolean>(true);
  const [copied, setCopied] = useState<boolean>(false);

  useEffect(() => {
    const fetchBrief = async () => {
      setLoading(true);
      try {
        const data = await projectApi.generateContextBrief(projectId);
        setBrief(data);
      } catch (err) {
        console.error('Failed to generate project brief:', err);
      } finally {
        setLoading(false);
      }
    };
    fetchBrief();
  }, [projectId]);

  const handleCopyMarkdown = () => {
    if (!brief) return;

    const md = `# ${brief.projectName} - Project Context Brief
Generated by ContextOS on ${new Date(brief.generatedAt).toLocaleString()}

## Project Overview
${brief.projectOverview}

## Current State
${brief.currentState}

## Recommended Starting Point
${brief.recommendedStartingPoint}

## Important Decisions
${brief.importantDecisions.map((d) => `* **${d.title}** (${d.date} by ${d.madeBy}): ${d.description}`).join('\n')}

## Current Blockers & Open Loops
${brief.currentBlockers.map((b) => `* [${b.priority}] **${b.title}**: ${b.resolution}`).join('\n')}

## Major Milestones
${brief.majorMilestones.map((m) => `* [${m.status}] ${m.title}`).join('\n')}

## Key Team Members
${brief.keyPeople.map((p) => `* **${p.name}** - ${p.role}`).join('\n')}
`;

    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-md p-4 overflow-y-auto">
      <div className="relative w-full max-w-3xl max-h-[90vh] flex flex-col rounded-3xl glass-panel border border-brand-500/30 shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="p-6 border-b border-border flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-brand-500/10 border border-brand-500/30 text-brand-400">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2 mb-1">
                <h3 className="text-lg font-bold text-white">Project Handover Context Brief</h3>
                {brief?.aiSource === 'gemini' ? (
                  <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-indigo-500/20 border border-indigo-500/30 text-indigo-300 text-[10px] font-semibold">
                    <Sparkles className="w-3 h-3 text-amber-300 animate-pulse" />
                    <span>Gemini Live AI</span>
                  </span>
                ) : (
                  <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-amber-500/15 border border-amber-500/30 text-amber-300 text-[10px] font-semibold">
                    <span>Continuity Engine</span>
                  </span>
                )}
              </div>
              <p className="text-xs text-slate-400">
                Instant onboarding document for teammates, managers, and project takeovers.
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopyMarkdown}
              className="px-3.5 py-1.5 rounded-xl bg-surface-100 hover:bg-surface-50 border border-border text-xs font-semibold text-slate-200 flex items-center gap-1.5 transition-all"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4 text-brand-400" />}
              <span>{copied ? 'Copied MD' : 'Copy Brief'}</span>
            </button>

            <button
              onClick={handlePrint}
              className="p-2 rounded-xl bg-surface-100 hover:bg-surface-50 border border-border text-slate-400 hover:text-white transition-all hidden sm:block"
              title="Print Brief"
            >
              <Printer className="w-4 h-4" />
            </button>

            <button
              onClick={onClose}
              className="p-2 rounded-xl bg-surface-100 hover:bg-surface-50 text-slate-400 hover:text-white border border-border transition-all"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6 md:p-8 space-y-6">
          {loading ? (
            <LoadingState message="Generating comprehensive project handover brief..." isContextReconstructing={true} />
          ) : !brief ? (
            <div className="text-center p-8 text-slate-400 text-xs">Failed to load brief.</div>
          ) : (
            <div className="space-y-6 text-slate-200 text-xs leading-relaxed">
              {/* Overview & Current State */}
              <div className="p-5 rounded-2xl bg-surface-100/70 border border-border space-y-3">
                <div>
                  <h4 className="font-bold text-sm text-white mb-1">Project Overview</h4>
                  <p className="text-slate-300">{brief.projectOverview}</p>
                </div>
                <div className="pt-3 border-t border-border/40">
                  <h4 className="font-bold text-sm text-white mb-1">Current State</h4>
                  <p className="text-slate-300">{brief.currentState}</p>
                </div>
              </div>

              {/* Recommended Starting Point */}
              <div className="p-4 rounded-2xl bg-brand-500/10 border border-brand-500/30 flex items-start gap-3">
                <Sparkles className="w-5 h-5 text-amber-300 shrink-0 mt-0.5" />
                <div>
                  <h4 className="font-bold text-white mb-0.5">Recommended Starting Point</h4>
                  <p className="text-slate-300">{brief.recommendedStartingPoint}</p>
                </div>
              </div>

              {/* Important Decisions */}
              <div>
                <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider flex items-center gap-1.5 mb-3">
                  <GitCommit className="w-4 h-4 text-brand-400" />
                  <span>Important Decisions (ADR)</span>
                </h4>
                <div className="space-y-2">
                  {brief.importantDecisions.map((d, i) => (
                    <div key={i} className="p-3 rounded-xl bg-surface-100 border border-border">
                      <div className="flex justify-between font-semibold text-slate-100 mb-0.5">
                        <span>{d.title}</span>
                        <span className="text-[10px] text-slate-500 font-mono">{d.date}</span>
                      </div>
                      <p className="text-slate-400 text-[11px]">{d.description}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Current Blockers */}
              {brief.currentBlockers.length > 0 && (
                <div>
                  <h4 className="text-xs font-bold text-rose-400 uppercase tracking-wider flex items-center gap-1.5 mb-3">
                    <AlertTriangle className="w-4 h-4 text-rose-400" />
                    <span>Current Blockers</span>
                  </h4>
                  <div className="space-y-2">
                    {brief.currentBlockers.map((b, i) => (
                      <div key={i} className="p-3 rounded-xl bg-rose-500/10 border border-rose-500/30 text-rose-200">
                        <span className="font-bold">{b.title}</span>
                        <p className="text-[11px] text-rose-300/80 mt-0.5">{b.resolution}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Key People */}
              <div>
                <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider flex items-center gap-1.5 mb-3">
                  <Users className="w-4 h-4 text-accent-cyan" />
                  <span>Key Project Contributors</span>
                </h4>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
                  {brief.keyPeople.map((p, i) => (
                    <div key={i} className="p-2.5 rounded-xl bg-surface-100 border border-border">
                      <p className="font-bold text-slate-200">{p.name}</p>
                      <p className="text-[10px] text-slate-400">{p.role}</p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
